# numpy

## 작업 시간 비교

In [1]:
import numpy as np
import datetime
#list 생성
li = range(1,1000000)
#현재 시간 저장 및 출력
s = datetime.datetime.now()
print("리스트 작업 시작 시간:", s)
#li의 각 요소에 10을 곱하기
for i in li:
    i = i * 10
s = datetime.datetime.now()
print("리스트 작업 종료 시간:", s)

#ndarray 생성
ar = np.arange(1,1000000)
s = datetime.datetime.now()
print("ndarray 작업 시작 시간:", s)
ar = ar * 10
s = datetime.datetime.now()
print("ndarray 작업 종료 시간:", s)

리스트 작업 시작 시간: 2021-09-02 01:00:35.898469
리스트 작업 종료 시간: 2021-09-02 01:00:36.115702
ndarray 작업 시작 시간: 2021-09-02 01:00:36.121425
ndarray 작업 종료 시간: 2021-09-02 01:00:36.130689


<font size='3'>ndarray</font> 
- 배열을 생성하는 가장 기본적인 함수는 array() 함수
- numpy.array(iterator객체 – 순차적인 객체) 형태로 생성하는데 데이터를 복제해서 생성
- dtype 속성을 이용해서 데이터의 자료형을 명시할 수 있지만 설정하지 않으면 데이터의 자료형은 numpy가 추정해서 모두 동일한 자료형으로 생성
- print 함수를 이용해서 변수의 이름을 출력하면 데이터 전부를 출력
- 데이터의 자료형은 dtype 속성으로 확인 가능
- ndim 속성은 배열의 차원
- shape 속성은 각 차원의 크기를 저장한 정수 튜플
- 배열이름[인덱스]를 이용해서 배열의 데이터 요소에 접근 가능
- 2차원 이상인 경우는 [행인덱스, 열인덱스]로 접근


##배열 생성 과 속성 확인

In [2]:
import numpy
#list를 이용해서 array 생성
ar = numpy.array([1, 2, 3])

##생성된 데이터의 자료형 확인
print(type(ar)) 

#차원 확인 - 1차원 3개의 데이터로 구성
print (ar.shape) 

#2차원 배열 만들기
br = numpy.array([[1,2,3],[4,5,6]]) 

#배열 출력
print(br)

#배열의 차원 확인
print (br.shape) 

#배열의 메모리 크기 확인
print(br.nbytes)

<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
48


<font size='3'>ndarray 생성</font> 
- 파이썬의 내장 함수인 range()와 유사하게 배열 객체를 만들어주는 함수는 arange()
<br/>numpy.arange([start, ]stop, [step, ]dtype=None)

- 시작점과 끝점을 균일 간격으로 나눈 값들을 이용해서 생성해주는 linspace()
<br/>numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


In [3]:
import numpy
# 1차원 배얼 [0,1,2, ... ,9] 생성
ar = numpy.arange(10)
print(ar)
print()

# start, end, num-points
ar = numpy.linspace(0, 1, 6)  
print(ar)
print()

# start, end, num-points, 마지막 포인트는 제외
ar = numpy.linspace(0, 1, 5, endpoint=False)
print(ar)
print()

[0 1 2 3 4 5 6 7 8 9]

[0.  0.2 0.4 0.6 0.8 1. ]

[0.  0.2 0.4 0.6 0.8]



<font size='3'>특수 행렬 생성</font> 
- zeros(), ones() 라는 함수들은 각각 0과 1로 채원진 배열을 생성하는데 차수를 정수 혹은 튜플로 설정
- zeros_like 나 ones_like 함수는 배열을 매개변수로 받아서 동일한 모양의 배열을 생성하는데 기존 데이터는 제거하고 0이나 1로 채움
- empty 나 empty_like 함수는 값을 초기화하지 않는 배열을 생성
- 대각행렬을 위한 eye() 함수와 diag() 함수도 존재
- eye() 함수는 단위행렬을 생성
- eye(N, M=, k=, dtype=): M은 열 수, k는 대각 위치(대각일 때가 0), dtype은 자료형
- diag()는 주어진 정방행렬에서 대각요소만 뽑아내서 벡터를 생성

In [4]:
import numpy
b1 = numpy.ones(10) # 1로 채원진 10 크기의 (1차원) 배열 생성
print(b1)
print()

b2 = numpy.zeros((5,5)) # 0으로 채원진 5x5 크기의 배열 생성
print(b2)
print()

#2*2 단위 행렬 생성
ar = numpy.eye(2, dtype=int)
print(ar)
print()

#3*3 행렬을 만들고 가운데에서 대각선 방향으로 위쪽에 1을 채움
ar = numpy.eye(3, k=1)
print(ar)
print()

#3*4 행렬을 만들고 가운데에서 대각선 방향으로 위쪽에 1을 채움
ar = numpy.eye(3, M=4, k=1)
print(ar)
print()

#9개짜리 일차원 배열을 3*3행렬로 변환
ar = numpy.arange(9).reshape((3,3))
print(ar)
print()

br = numpy.diag(ar)
print(br)
print()

#중앙의 대각선에서 위나 아래 한칸 이동해서 데이터를 가져와서 벡터를 생성
cr = numpy.diag(ar,k=1)
print(cr)
print()

dr = numpy.diag(ar, k=-1)
print(dr)
print()

er = numpy.empty( (2,2) ) # 가비지 값으로 채원진 2x2 크기의 배열 생성
print(er)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1 0]
 [0 1]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 4 8]

[1 5]

[3 7]

[[5.e-324 0.e+000]
 [0.e+000 5.e-324]]


<font size='3'>ndarray의 자료형</font>
- 배열을 생성할 때 dtype이라는 옵션을 이용해서 설정 가능
<br/>numpy.array([xx, xx], dtype=numpy.Type)
- dtype이라는 속성을 이용해서 확인 가능
- 서로 다른 데이터 타입의 데이터를 이용해서 생성할 때 대입하면 형 변환을 해서 하나의 자료형 배열이 생성
- 정수와 실수가 혼합되어 있다면 실수, 숫자와 문자열이 혼합되어 있다면 문자열로 생성
- astype 함수를 이용해서 데이터의 타입을 변경한 배열을 생성할 수 있음
- numpy의 자료형
  <br/> 정수 자료형: int8, 16, 32, 64, uint8, uint16, uint32, uing64
  <br/> 실수 자료형: float16, 32, 64, 128
  <br/> 복소수 자료형: complex64, 128, 256
  <br/> boolean: bool
  <br/> 객체: object
  <br/> 문자열: string_
  <br/> 유니코드: unicode_

In [6]:
import numpy as np
#정수로만 구성
ar = np.array([1,2,3])
print("타입 확인:",ar.dtype);

#문자열로만 구성
ar = np.array(['12', '2' ,'3'])
print("타입 확인:",ar.dtype);

#정수와 실수 혼합
ar = np.array([3, 2.9, 4])
print("타입 확인:",ar.dtype);

#문자열과 숫자 혼합
ar = np.array([3, 2.9, '4'])
print("타입 확인:",ar.dtype);

#문자열과 정수 혼합이지만 정수로 설정
ar = np.array([3, 2, '4'], dtype=np.int32)
print("타입 확인:",ar.dtype);

#실수 타입으로 변경
ar = ar.astype(np.string_)
print("타입 확인:",ar.dtype);

타입 확인: int64
타입 확인: <U2
타입 확인: float64
타입 확인: <U32
타입 확인: int32
타입 확인: |S11


<font size='3'>행렬 변환</font> 
- 배열은 reshape() 함수를 이용하여 각 차원의 개수를 튜플로 대입해서 다른 차원 또는 데이터의 개수를 조절해서 변경 가능 – 데이터를 동일하게 유지하면서 배열의 구조를 변경
- reshape 함수에 -1을 대입하면 1차원 배열로 변환
- flattern 함수를 이용하면 다차원 배열을 1차원으로 변환 가능
- reshape는 데이터를 유지하지만 flattern은 새로운 배열을 리턴


In [7]:
import numpy
# 1차원 배열 [0,1,2, ... ,9] 생성
ar = numpy.arange(10)  
print(ar)
print()

# 같은 요소를 가지고 2x5 배열로 변형
ar = ar.reshape(2, 5)
print(ar)
print()

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]



In [ ]:
import numpy
# 행렬을 생성
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#1차원으로 변환 - 모양만 변경
ar = matrix.reshape(-1)
print(ar)
print()

#1차원으로 변환 - 데이터를 복제
br = matrix.flatten()
print(br)
print()

#원본 데이터 변경
matrix[0,0] = 100

#원본이 변경되었으므로 같이 변경됨 
print(ar)
print()

#복제를 했으므로 아무런 영향이 없음 
print(br)

[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]

[100   2   3   4   5   6   7   8   9]

[1 2 3 4 5 6 7 8 9]


## 인덱싱
1차원 배열의 인덱스는 list 와 유사하게 적용
배열명[인덱스] 을 이용하면 배열에서 인덱스 번째 데이터를 리턴
인덱스에 음수를 대입하면 뒤에서부터 리턴
[시작 위치 : 종료 위치] 를 이용하면 시작 위치부터 종료 위치 앞까지 리턴
[시작 위치:] 이면 시작 위치부터 끝까지
[:종료 위치]: 처음부터 종료 위치까지
[:] 는 전체
2차원 이상의 배열에서 인덱스는 [행번호][열번호]의 형태로 입력해도 되지만 [행번호, 열번호]를 이용 가능
2차원 이상의 배열에서 인덱스를 생략하면 생략된 인덱스 전체


In [ ]:
import numpy as np

# 하나의 행을 갖는 배열 생성
vector = np.array([1, 2, 3, 4, 5, 6])

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# vector의 세 번째 원소를 선택합니다.
print(vector[2])
print()

# matrix의 두 번째 행, 두 번째 열의 원소를 선택합니다.
print(matrix[1,1])
print()

# 벡터에 있는 모든 원소를 선택합니다.
print(vector[:])
print()

# 세 번째 원소를 포함하여 그 이전의 모든 원소를 선택합니다.
print(vector[:3])
print()

# 세 번째 이후의 모든 원소를 선택합니다.
print(vector[3:])
print()

# 마지막 원소를 선택합니다.
print(vector[-1])
print()

# 행렬에서 첫 번째 두 개의 행과 모든 열을 선택합니다.
print(matrix[:2,:])
print()

# 모든 행과 두 번째 열을 선택합니다.
print(matrix[:,1:2])

3

5

[1 2 3 4 5 6]

[1 2 3]

[4 5 6]

6

[[1 2 3]
 [4 5 6]]

[[2]
 [5]
 [8]]


## 슬라이싱 – 인덱스를 이용해서 데이터 가져오기
인덱스를 이용해서 가져온 결과는 copy가 되지 않고 링크만 전달
복제를 하고자 하는 경우는 .copy()를 호출


In [ ]:
import numpy
ar = numpy.array([1,2,3,4,5])
#복제된 데이터가 아니고 현재 데이터의 포인터만 가져옴
br = ar[0:3]

#복제된 데이터
cr = ar[0:3].copy()

#원본 데이터 변경
ar[0]=10
print(ar)
print()

#복제된 데이터가 아니므로 원본 데이터의 변경이 반영됨
print(br)
print()

#복제된 데이터 이므로 반영되지 않음
print(cr)

[10  2  3  4  5]

[10  2  3]

[1 2 3]


## Fancy Indexing
인덱스에 리스트를 사용해서 배열로부터 Indexing 하는 것
Fancy Indexing은 copy를 생성
특정 순서로 다차원 배열의 행(row)과 열(column)을 Fancy Indexing
특정 순서로 행(row)을 fancy indexing 한 후에 전체 행을 ＇:＇로 선택하고 특정 칼럼을 순서대로 배열을 사용해서 indexing을 한번 더 수행
numpy.ix_ 함수를 사용해서 첫번째 매개변수인 배열1로 특정 행(row)을 지정하고 두번째 매개변수인 배열2로 특정 열(column)을 지정


In [8]:
import numpy

ar = numpy.empty((10, 5)) #gabage 값을 갖는 10행 5열의 배열을 생성
for i in range(10):
    ar[i] = i   #각 행의 모든 데이터를 i 값으로 채움
print(ar)
print()

br = ar[[1,3,5,7]] #1,3,5,7 행만 선택
print(br)
print()

cr = ar[[0,1], [3,4]] #[0,3],[1,4] 만 선택
print(cr)
print()

dr = ar[[0,1]][:,[3,4]] #0번 행의 3번째와 4번째 1번 행의 3번째와 4번째 데이터 선택
print(dr)
print()

#fancy 색인은 copy 이므로  ar의 내용이 변경되더라도 dr은 변경이 없음
ar[0,3] = 100
print(dr)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9.]]

[[1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [5. 5. 5. 5. 5.]
 [7. 7. 7. 7. 7.]]

[0. 1.]

[[0. 0.]
 [1. 1.]]

[[0. 0.]
 [1. 1.]]


In [7]:
ar = numpy.empty((10, 5)) #gabage 값을 갖는 10행 5열의 배열을 생성
for i in range(10):
    ar[i] = i   #각 행의 모든 데이터를 i 값으로 채움
#일차원 배열로 리턴
print(ar[0])
print()

print(ar[0, :])
print()

#이차원 배열로 리턴
print(ar[[0]])

[0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]]


## 불리언 색인
배열에 조건 연산자를 사용하면 결과가 bool의 배열로 리턴
인덱스에 bool 배열을 적용하면 결과가 True인 데이터만 리턴


In [4]:
import numpy
ar = numpy.arange(20).reshape(5, 4)
br = numpy.array(['A', "B", 'C', 'A', 'C'])
print(br == 'A') #데이터가 A인 경우는 True 그렇지 않으면 False
print()
print(ar[br == 'A']) #True 인 행만 반환
print()
print(ar[br == 'A', 2]) #열을 2번째만 반환
print()
print(ar[br == 'A', 0:2]) #열을 0부터 2앞까지 반환
print()
#데이터 변환
ar[br == 'A'] = 100
print(ar)
print()
print( (br == 'A') | (br == 'B') )

[ True False False  True False]

[[ 0  1  2  3]
 [12 13 14 15]]

[ 2 14]

[[ 0  1]
 [12 13]]

[[100 100 100 100]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 100 100 100]
 [ 16  17  18  19]]

[ True  True False  True False]


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

<font size='3'>ndarray의 연산</font>
- 배열과 Scala 데이터의 연산은 배열의 모든 요소에 Scala 데이터를 연산해서 결과를 리턴
- 차원이 동일하고 차원의 크기가 같은 배열끼리의 연산은 동일한 위치의 데이터끼리 연산을 수행해서 결과를 리턴하는데 차원의 크기가 다르면 연산을 하지 못하고 에러
- 차원이 다르면 브로드 캐스팅 연산을 수행 – 작은 차원의 데이터를 큰 차원의 모든 데이터와 연산 수행(배열에 차원을 추가하거나 반복해서 수행)

In [11]:
import numpy
ar = numpy.array([1,2,3])
br = numpy.array([4,5,6])
cr = numpy.array([[6,7,8], [10,20,30]])
result = ar * 2 #배열의 모든 요소에 2를 곱한 결과
print(result)
print()

result = ar + br; #배열 간의 덧셈: 동일한 위치간의 덧셈을 한 결과
print(result)
print()

result = ar + cr #작은 차원인 ar 의 모든 데이터를 cr에 덧셈
print(result)
print()

dr = numpy.array([1,2])
result = ar + dr #차원은 1차원으로 같은데 데이터 개수가 달라서 에러

[2 4 6]

[5 7 9]

[[ 7  9 11]
 [11 22 33]]



ValueError: ignored

## 배열의 모든 요소에 동일한 함수 적용
함수를 numpy의 vectorize 함수에 대입해서 벡터화 된 함수를 리턴받은 후 리턴 받은 함수에게 ndarray를 대입하면 모든 요소에게 동일한 함수를 적용한 후 결과를 리턴



In [8]:
#벡터화된 연산
import numpy 

# 행렬을 만듭니다.
matrix = numpy.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 100을 더하는 함수를 생성
add_100 = lambda i: i + 100

# 벡터화된 함수를 만듭니다.
vectorized_add_100 = numpy.vectorize(add_100)

# 행렬의 모든 원소에 함수를 적용합니다.
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## ndarray의 연산
동일한 크기를 갖는 배열 간의 비교 연산(>, >=, <, <=, ==, !=)은 동일한 위치의 데이터를 비교해서 True 또는 False로 리턴해서 배열로 결과를 리턴 – numpy의 equal, not_equal, greater, greater_equal, less, less_equal 함수를 이용해도 가능
동일한 크기를 갖는 배열 간의 할당 연산: Add AND (m += n), Subtract AND (m -= n), Multiply AND (m *= n), Divide AND (m /= n), Floor Division (m //= n), Modulus AND (m %= n), Exponent AND (m **= n)
배열 간의 논리 연산
0이나 None 인 데이터는 Fasle 나머지는 True로 간주

numpy.logical_and(a, b) : 두 배열의 원소가 모두 True이면 True이고 그렇지 않으면 False
numpy.logical_or(a, b) :  두 배열의 원소가 모두 False 이면 False 그렇지 않으면 True
numpy.logical_xor(a, b) : 두 배열의 원소가 같으면 False 그렇지 않으면 True 반환
소속 여부 판단 연산 : in, not in – 배열(혹은 리스트)에 특정 객체가 들어있으면 True를 반환, 존재하지 않으면 False를 반환


In [10]:
import numpy
ar = numpy.array([1,2,3])
br = numpy.array([4,2,6])

#각 요소가 같은지 비교
print(numpy.equal(ar, br))
print(ar == br)
print()

#각 요소가 다른지 비교
print(numpy.not_equal(ar, br))
print(ar != br)
print()

#ar의 요소가 큰지 확인
print(numpy.greater(ar, br))
print(numpy.greater_equal(ar, br))
print()

#ar의 요소가 작은지 확인
print(numpy.less(ar, br))
print(numpy.less_equal(ar, br))

[False  True False]
[False  True False]

[ True False  True]
[ True False  True]

[False False False]
[False  True False]

[ True False  True]
[ True  True  True]


In [ ]:
import numpy
ar = numpy.array([1,0,3])
br = numpy.array([4,2,3])

#논리 연산
print(numpy.logical_and(ar, br))
print(numpy.logical_or(ar, br))
print(numpy.logical_xor(ar, br))
print()

#데이터의 소속 여부 확인
print(1 in ar)
print(2 in ar)

[ True False  True]
[ True  True  True]
[False  True False]

True
False


## 배열의 전치 와 축 변경
배열의 전치는 T라는 이름의 특수한 속성이 있음
transpose 라는 함수를 이용해서 전치할 수 있음

In [15]:
ar = numpy.arange(15).reshape((3, 5))
print(ar)
print()

print(ar.T)
print()

print(ar.transpose(1,0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


<font size='3'>난수 – numpy.random</font>
- numpy는 효율적으로 무작위 샘플을 만들 수 있는 numpy.random 모듈을 제공
- numpy.random.seed(seed=시드번호): 시드번호를 가지고 난수를 생성
- permutation(): 정수를 입력하면 0부터 입력된 정수 이전 까지의 배열을 생성해서 숫자를 랜덤하게 배치해서 리턴하고 배열을 대입하면 배열의 데이터를 임의로 배치한 배열을 리턴
- shuffle(): permutation과 거의 유사한 기능
- rand() 함수는 균등 분포에서 표본 추출
- randint(): 주어진 최소/최대 범위 안에서 난수를 추출하며 size를 이용해서 개수 지정 가능
- normal(size=개수 또는 shape): 정규 분포에서 size를 생략하면 1개의 데이터만 리턴하고 개수를 입력하면 그 개수에 해당하는 데이터를 배열로 리턴하고 shape 형태를 입력하면 shape에 맞게 생성
- binomial(n, p, size): 이항분포로부터의 무작위 추출 함수로 n은 0부터 나올 수 있는 숫자의 범위로 정수 p는 확률이고 size는 개수

In [17]:
import numpy
print(numpy.random.normal(size=5)) #5개의 난수 생성 - 랜덤
print()
print(numpy.random.normal(size=(2, 3))) #2행 3열의 난수 생성
print()
numpy.random.seed(seed=42) #시드 설정
print(numpy.random.normal(size=5)) #5개의 난수 생성 - 실행할 때마다 동일한 값

[ 0.51421884  0.22117967 -1.07004333 -0.18949583  0.25500144]

[[-0.45802699  0.43516349 -0.58359505]
 [ 0.81684707  0.67272081 -0.10441114]]

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]


<font size='3'>기본 통계 함수</font>
- sum: 배열에 있는 모든 원소의 합을 계산해서 리턴
- mean, median, std, var: 평균값, 중간값, 표준편차, 분산
- percentile은 배열과 백분위 값을 받아서 백분위에 해당하는 데이터를 리턴
- 2차원 이상의 배열에서 axis 옵션을 이용하면 행이나 열 단위로 계산이 가능

In [18]:
import numpy
ar = numpy.array([1, 2, 4, 5, 5, 7, 9, 10, 13, 18, 21])
print('배열의 합계:', numpy.sum(ar))
print('배열의 평균:', numpy.mean(ar))
print('배열의 중간값:', numpy.median(ar))
print('배열의 표준편차:', numpy.std(ar))
print('배열의 분산:', numpy.var(ar))
print('배열에서 3/4에 해당하는 값:', numpy.percentile(ar, 75))

배열의 합계: 95
배열의 평균: 8.636363636363637
배열의 중간값: 7.0
배열의 표준편차: 6.138888369503321
배열의 분산: 37.68595041322314
배열에서 3/4에 해당하는 값: 11.5


In [19]:
import numpy
#print(help(numpy.sum))

ar = numpy.array([[1, 2, 4, 5, 5], [7, 9, 10, 13, 18]])
#배열 전체의 합계
print(numpy.sum(ar))
print('===============')
#열 단위의 합계
print(numpy.sum(ar, axis=0))
print('===============')
#행 단위의 합계
print(numpy.sum(ar, axis=1))

74
[ 8 11 14 18 23]
[17 57]


In [20]:
import numpy

# 행렬을 만듭니다.
matrix = numpy.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 각 행에서 최댓값
print(numpy.max(matrix, axis=1))
print()

#결과가 동일한 차원의 배열
print(numpy.max(matrix, axis=1, keepdims=True))

[3 6 9]

[[3]
 [6]
 [9]]


In [29]:
ar = numpy.random.randn(100)
print(ar)
print()
print((ar > 0).sum())

[ 0.40405086  1.8861859   0.17457781  0.25755039 -0.07444592 -1.91877122
 -0.02651388  0.06023021  2.46324211 -0.19236096  0.30154734 -0.03471177
 -1.16867804  1.14282281  0.75193303  0.79103195 -0.90938745  1.40279431
 -1.40185106  0.58685709  2.19045563 -0.99053633 -0.56629773  0.09965137
 -0.50347565 -1.55066343  0.06856297 -1.06230371  0.47359243 -0.91942423
  1.54993441 -0.78325329 -0.32206152  0.81351722 -1.23086432  0.22745993
  1.30714275 -1.60748323  0.18463386  0.25988279  0.78182287 -1.23695071
 -1.32045661  0.52194157  0.29698467  0.25049285  0.34644821 -0.68002472
  0.2322537   0.29307247 -0.71435142  1.86577451  0.47383292 -1.1913035
  0.65655361 -0.97468167  0.7870846   1.15859558 -0.82068232  0.96337613
  0.41278093  0.82206016  1.89679298 -0.24538812 -0.75373616 -0.88951443
 -0.81581028 -0.07710171  0.34115197  0.2766908   0.82718325  0.01300189
  1.45353408 -0.26465683  2.72016917  0.62566735 -0.85715756 -1.0708925
  0.48247242 -0.22346279  0.71400049  0.47323762 -0.0

<font size='3'>배열 통계</font>
- argmin, argmax: 최소값과 최대값의 인덱스
- prod(): 2차원 배열의 경우 axis=0 이면 같은 열(column)의 방향으로 배열 원소를 곱하며 axis=1 이면 같은 행(row)의 방향으로 원소 간 곱
- nanprod(): NaN (Not a Numbers) 을 ＇1＇(one)로 간주하고 배열 원소 간 곱
- nansum(): NaN (Not a Numbers)을 '0'(zero)으로 간주하고 배열 원소 간 더하기
- cumprod(): axis=0 이면 같은 행(column)의 위에서 아래 방향으로 배열 원소들을 누적(cumulative)으로 곱해 나가며, axis=1 이면 같은 열(row)에 있는 배열 원소 간에 왼쪽에서 오른쪽 방향으로 누적으로 곱
- cumsum(): axis=0 이면 같은 행(column)의 위에서 아래 방향으로 배열 원소들을 누적(cumulative)으로 합해 나가며, axis=1 이면 같은 열(row)에 있는 배열 원소 간에 왼쪽에서 오른쪽 방향으로 누적으로 합
- diff(): 배열 원소 간 n차 차분 구하기 – n 값은 기본값이 1로 설정되어 있어서 한 번 차분을 해서 리턴하고 2를 대입하면 차분의 차분을 리턴
- 함수 들의 결과가 하나의 데이터로 리턴되는 경우 keepdims 옵션에  True를 설정하면 array로 리턴

In [21]:
import numpy
b = numpy.array([1, 2, 3, 4])
c = numpy.array([[1, 2], [3, 4]])
print(numpy.prod(b)) # 1*2*3*4
print(numpy.prod(c, axis=0))  # [1*3, 2*4]
print(numpy.prod(c, axis=1))  # [1*2, 3*4]
print(numpy.sum(b)) # [1+2+3+4]
print(numpy.sum(b, keepdims=True))
print(numpy.sum(c, axis=0))  # [1+3, 2+4]
print(numpy.sum(c, axis=1) ) # [1+2, 3+4]

24
[3 8]
[ 2 12]
10
[10]
[4 6]
[3 7]


In [22]:
import numpy
b = numpy.array([1, 2, 3, 4])
c = numpy.array([[1, 2], [3, 4]])
print(numpy.cumprod(b))# [1, 1*2, 1*2*3, 1*2*3*4]
print(numpy.cumprod(c, axis=0))  # [[1, 2], [1*3, 2*4]]
print(numpy.cumprod(c, axis=1))  # [[1, 1*2], [3, 3*4]]
print(numpy.cumsum(b))# [1, 1+2, 1+2+3, 1+2+3+4]
print(numpy.cumsum(c, axis=0))  # [[1, 2], [1+3, 2+4]]
print(numpy.cumsum(c, axis=1))  # [[1, 1+2], [3, 3+4]]

[ 1  2  6 24]
[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]
[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [23]:
import numpy
g = numpy.array([1, 2, 4, 10, 13, 20])
print(numpy.diff(g))  # [2-1, 4-2, 10-4, 13-10, 20-13]
print(numpy.diff(g, n=2))  # [2-1, 6-2, 3-6, 7-3]

[1 2 6 3 7]
[ 1  4 -3  4]


<font size='3'>소수 관련 함수</font>
- numpy.around(a) : 0.5를 기준으로 올림 혹은 내림
- numpy.round_(a, N) : N 소수점 자릿수까지 반올림
- numpy.rint(a) : 가장 가까운 정수로 올림 혹은 내림
- numpy.fix(a) : '0' 방향으로 가장 가까운 정수로 올림 혹은 내림
- numpy.ceil(a) : 각 원소 값보다 크거나 같은 가장 작은 정수 값 (천장 값)으로 올림
- numpy.floor(a) : 각 원소 값보다 작거나 같은 가장 큰 정수 값 (바닥 값)으로 내림
- numpy.trunc(a) : 각 원소의 소수점 부분은 잘라버리고 정수 값만 남김

In [24]:
import numpy
ar = numpy.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print(numpy.around(ar))
print(numpy.round_(ar, 1))
print(numpy.rint(ar))
print(numpy.fix(ar))
print(numpy.ceil(ar))
print(numpy.floor(ar))
print(numpy.trunc(ar))

[-5. -2.  0.  2.  3.  4.]
[-4.6 -2.2  0.   1.6  3.4  4.1]
[-5. -2.  0.  2.  3.  4.]
[-4. -2.  0.  1.  3.  4.]
[-4. -2.  0.  2.  4.  5.]
[-5. -3.  0.  1.  3.  4.]
[-4. -2.  0.  1.  3.  4.]


<font size='3'>None은 numpy.nan</font>

<font size='3'>숫자 처리 함수</font>
- numpy.abs(x), numpy.fabs(x): 배열 원소의 절대값 (absolute value)
- numpy.sqrt(y): 배열 원소의 제곱근(Square Root)
- numpy.square(y): 배열 원소의 제곱값 (square value) 범용 함수 
- numpy.modf(z): 배열 원소의 정수와 소수점을 구분하여 2개의 배열 반환
- numpy.sign(x): 열 원소의 부호 판별 함수 -> 1 (positive), 0(zero), -1(negative)

<font size='3'>논리 함수</font>
- numpy.isnan(x): NaN(Not a Number) 포함 여부 확인
- numpy.isfinite(x): 유한수(finite number) 포함 여부 확인
- numpy.isinf(x): 배열에 무한수(infinite number) 포함 여부 확인
- numpy.logical_not(condition): 배열 원소가 조건을 만족하지 않는 경우 참 반환

In [25]:
import numpy
ar = numpy.array([10, 1, 2, 3, 4, numpy.nan])
print(numpy.isnan(ar)) #isnan을 이용해서 nan 데이터가 있는지 확인
br = ar[numpy.logical_not(numpy.isnan(ar))] #nan 데이터를 제외하고 가져오기
print(br)
print(numpy.logical_not( br <= 2 )) #2보다 큰 데이터가 있는지 확인
cr = br[numpy.logical_not( br <= 2 )] #2보다 큰 데이터 추출
print(cr)

[False False False False False  True]
[10.  1.  2.  3.  4.]
[ True False False  True  True]
[10.  3.  4.]


<font size='3'>이항 함수: 배열 2개를 가지고 작업하는 함수</font>
- add, subtract, multiply, divide, floor_divide(몫만 가져오기)
- power(첫번째 배열의 데이터에 두번째 배열의 데이터만큼 제곱)
- maximum, fmax(NaN 데이터 무시), minimum, fmin
- mod
- copysign(첫번째 배열의 데이터 부호를 두번째 배열의 데이터 부호로 변경)
- greater, greater_equal, less, less_equal, equal, not_equal
- logical_and, logical_or, logical_택

<font size='3'>where(boolean 배열, True일 때 선택할 데이터, False일 때 선택할 데이터)</font>

In [26]:
import numpy
ar = numpy.array([1, 2, 3, 4])
br = numpy.array([5, 6, 7, 8])
print(ar + br)
print(numpy.add(ar, br))
cond = [True, False, False, True]
print(numpy.where(cond, ar, br))

[ 6  8 10 12]
[ 6  8 10 12]
[1 6 7 4]


<font size='3'>집합 관련 함수</font>
- unique(): 중복을 제거
- intersect1d(): 교집합
- union1d(): 합집합
- in1d(): 데이터의 존재 여부를 boolean 배열로 리턴
- setdiff1d(): 차집합
- setxor1d(): 한쪽에만 있는 데이터의 집합 

In [30]:
import numpy
ar = numpy.array([90, 40, 30, 78, 30])
#중복 제거
print("중복제거:", numpy.unique(ar))
br = numpy.array([30, 45, 76, 90])
#교집합
print('교집합:', numpy.intersect1d(ar, br))
#합집합
print('합집합:',numpy.union1d(ar, br))
#소속여부
print('소속여부:',numpy.in1d(ar, br))
#차집합
print('차집합',numpy.setdiff1d(ar, br))
#한쪽에만 속한 데이터
print(numpy.setxor1d(ar, br))

중복제거: [30 40 78 90]
교집합: [30 90]
합집합: [30 40 45 76 78 90]
소속여부: [ True False  True False  True]
차집합 [40 78]
[40 45 76 78]


## 배열 함수
numpy.concatenate: 여러 개의 배열을 한 개로 만들어주는 함수로 X축과 Y축 방향으로 합치는 두 가지 방법이 있으며 axis 라는 파라미터를 통해 제어함. 
- axis = 0: Y축 (세로 방향) 으로 연결
- axis = 1: X축 (가로 방향) 으로 연결


In [32]:
import numpy
ar = [1,2,3,4]
br = [5,6,7,8]
cr = numpy.concatenate((ar, br))
print(cr)
print()

ar = numpy.array([[1, 2], [3, 4]])
br = numpy.array([[5, 6], [7, 8]])
cr = numpy.concatenate((ar, br), axis = 0)
print(cr)
print()

cr = numpy.concatenate((ar, br), axis = 1)
print(cr)


[1 2 3 4 5 6 7 8]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


<font size='3'>ndarray.sort()</font>
- 배열의 데이터를 정렬
- numpy.sort()는 정렬한 결과를 리턴
- axis 매개변수는 정렬할 축 번호

In [40]:
import numpy
ar = numpy.array([90, 40, 30, 78])
ar.sort()
print(ar)
print()

br = numpy.sort(ar)
print(br)
print()

# 내림차순
cr = numpy.sort(ar)[::-1]
print(cr)
print()

ar.sort(kind='mergesort')
print(ar)
print()

ar = numpy.array([[90, 40, 50], [30, 78,27]])
ar.sort(axis=0)
print(ar)

[30 40 78 90]

[30 40 78 90]

[90 78 40 30]

[30 40 78 90]

[[30 40 27]
 [90 78 50]]


## numpy.concatenate: 여러 개의 배열을 한 개로 만들어주는 함수로 X축과 Y축 방향으로 합치는 두 가지 방법이 있으며 axis 라는 파라미터를 통해 제어함. 
- axis = 0: Y축 (세로 방향) 으로 연결
- axis = 1: X축 (가로 방향) 으로 연결


In [41]:
import numpy
ar = [1,2,3,4]
br = [5,6,7,8]
cr = numpy.concatenate((ar, br))
print(cr)
print()

ar = numpy.array([[1, 2], [3, 4]])
br = numpy.array([[5, 6], [7, 8]])
cr = numpy.concatenate((ar, br), axis = 0)
print(cr)
print()

cr = numpy.concatenate((ar, br), axis = 1)
print(cr)


[1 2 3 4 5 6 7 8]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


<font size='3'>numpy.split</font>
- 배열을 여러 개로 분할해주는 함수
- 나누는 방법은 X축, 그리고 Y축을 기준을 나누는 두 가지의 방법이 있으며 numpy.concatenate의 axis와 동일하게 작동 
두 번째 파라미터에 숫자 N을 넣으면 배열을 N개의 동일한 크기의 배열들로 나누고 리스트를 넣는다면 리스트 안의 숫자들 번째 인덱스에서 배열을 나눔

In [ ]:
import numpy
ar = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14 ,15, 16]])
print(ar)
print()
splitY = numpy.split(ar, 2, axis = 0) #x축 방향으로 2개로 나눔
print(splitY[0])
print(splitY[1])
print()
splitX = numpy.split(ar, [2, 3], axis = 1) #2번째 앞까지 나누고 3번째 앞까지 나누고 나머지
print(splitX[0])
print(splitX[1])
print(splitX[2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]


In [42]:
import numpy
ar = numpy.array([90, 40, 30, 78])
ar.sort()
print(ar)
br = numpy.sort(ar)
print(br)

ar = numpy.array([[90, 40, 50], [30, 78,27]])
ar.sort(axis=0)
print(ar)

[30 40 78 90]
[30 40 78 90]
[[30 40 27]
 [90 78 50]]


## 배열의 결합

In [44]:
#hstack: 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 생성
import numpy
a1 = numpy.ones((2, 3))
print(a1)
print()

a2 = numpy.zeros((2, 2))
print(a2)
print()

print(numpy.hstack([a1, a2]))


[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]]

[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


In [45]:
#vstack: 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열 생성
import numpy
a1 = numpy.ones((2, 2))
print(a1)
print()

a2 = numpy.zeros((2, 2))
print(a2)
print()

print(numpy.vstack([a1, a2]))


[[1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [46]:
#dstack

import numpy
c1 = numpy.array(range(1,13,1))
c2 = c1.reshape(3,4)
print(c2)
print()

d1 = numpy.array(range(101,113,1))
d2 = d1.reshape(3,4)
print(d2)
print()

print(numpy.dstack([c2, d2]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]

[[[  1 101]
  [  2 102]
  [  3 103]
  [  4 104]]

 [[  5 105]
  [  6 106]
  [  7 107]
  [  8 108]]

 [[  9 109]
  [ 10 110]
  [ 11 111]
  [ 12 112]]]


In [47]:
# stack
print(numpy.stack([c2, d2]))

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[101 102 103 104]
  [105 106 107 108]
  [109 110 111 112]]]


In [48]:
print(numpy.stack([c2, d2], axis=1))

[[[  1   2   3   4]
  [101 102 103 104]]

 [[  5   6   7   8]
  [105 106 107 108]]

 [[  9  10  11  12]
  [109 110 111 112]]]


In [49]:
# r_
print(numpy.r_[numpy.array([1, 2, 3]), numpy.array([4, 5, 6])])


[1 2 3 4 5 6]


In [50]:
# c_
print(numpy.c_[numpy.array([1, 2, 3]), numpy.array([4, 5, 6])])


[[1 4]
 [2 5]
 [3 6]]


In [51]:
#tile
a = numpy.array([[0, 1, 2], [3, 4, 5]])
print(numpy.tile(a, 2))
print()
print(numpy.tile(a, (3, 2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


## 배열의 데이터 저장 과 가져오기

In [55]:
ar = numpy.array([[0, 1, 2], [3, 4, 5]])
#파일로 저장
numpy.save('some_array.npy', ar)
#파일에서 읽어오기
print(numpy.load('some_array.npy'))
print()

br = numpy.arange(10)
numpy.savez('array_archive.npz', ar=ar, br=br)
print(numpy.load('array_archive.npz')['br'])

[[0 1 2]
 [3 4 5]]

[0 1 2 3 4 5 6 7 8 9]
